[package]
name = "crowdmark"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
chrono = { version = "0.4.42", features = ["serde"] }
regex = "1.12.2"
reqwest = { version = "0.12.23", features = ["cookies", "json", "multipart"] }
serde.workspace = true
serde_json = "1.0.145"
thiserror = "2.0.17"
uuid = { version = "1.18.1", features = ["v4"] }
